
version: "{branch}.{build}"

image: Visual Studio 2019

clone_folder: c:\projects\convey

environment:
        matrix:
                - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
                  ARCH: x86
                - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
                  ARCH: amd64
                - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
                  ARCH: x86_arm

build_script:
        cmd: |
                cd c:\projects\convey
                call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
                nmake

after_build:
        ps: |
                $d = 'c:\projects\convey'
                $convey_version = [regex]::Match([IO.File]::ReadAllText("$d\config.h"), 'VERSION\s*"([^"]+)"').captures.groups[1].value
                $ZIPBALL="$d\convey-" + $convey_version + "-" + ($env:ARCH -Replace ".*_") + ".zip"
                7z a $ZIPBALL $d\convey.exe $d\convey.pdb $d\LICENSE $d\README.md
                Push-AppveyorArtifact $ZIPBALL

deploy:
        release: convey-$(APPVEYOR_REPO_TAG_NAME)
        description: Convey serial port communication tool.
        provider: GitHub
        auth_token:
                secure: 3G2RxLQc+/+CDj6kNfeYG3tfVvSD4tAETGeP4MqxaFRipmyt7TsCjERm2LlkqIff
        artifact: c:\projects\convey\*.zip
        draft: false
        prerelease: false
        on:
                APPVEYOR_REPO_TAG: true

