version: "{branch}.{build}"

image: Visual Studio 2019

clone_folder: c:\projects\convey

environment:
        matrix:
                - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
                  ARCH: x86
                - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
                  ARCH: amd64

build_script:
        cmd: |
                cd c:\projects\convey
                call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
                nmake

after_build:
        ps: |
                $d='c:\projects\convey'
                $s=[IO.File]::ReadAllText("$d\config.h")
                $s -match 'VERSION\s*""([^^"]+)""'
                $convey_version = $Matches.1
                $ZIPBALL="$d\convey-" + $convey_version + "-" + $env:ARCH + ".zip"
                7z a $ZIPBALL $d\convey.exe $d\convey.pdb $d\LICENSE $d\README.md
                Push-AppveyorArtifact $ZIPBALL

